development:
  adapter: mysql2
  encoding: utf8
  database: user
  username: name
  password: password
  host: 127.0.0.1
production:
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: sample_app_production
  username: sample_app
  password: <%= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>
test:
  adapter: mysql2
  encoding: utf8
  database: user
  username: name
  password: password
  host: 127.0.0.1
